name: Deploy Memo App to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and Restart FastAPI
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ${{ secrets.EC2_PATH }}
            # Configure git to use HTTPS with token
            git remote set-url origin https://${{ secrets.TOKEN }}@github.com/Suryanshusingh123/opticall-mobile-backend.git
            # Pull the latest changes
            git pull origin main
            source venv/bin/activate
            uv pip install -r requirements.txt
            sudo systemctl restart memoapp-backend
          EOF
